language: node_js
node_js:
  - "4.0"

services:
  - mongodb

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - CXX=g++-4.8

before_script:
  - npm install -g gulp

script: gulp test
